// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHavoPPKQ44TJ2MnUSNpHqAtd6BHZ6D6A',
    appId: '1:873514032021:web:7754a5235d19427f41349c',
    messagingSenderId: '873514032021',
    projectId: 'thementr-f6c53',
    authDomain: 'thementr-f6c53.firebaseapp.com',
    storageBucket: 'thementr-f6c53.appspot.com',
    measurementId: 'G-TKFEP59119',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf7WbbZEYs5biY7RbLI2EBKpGbf-q8N3k',
    appId: '1:873514032021:android:a9b031c50b3acf1f41349c',
    messagingSenderId: '873514032021',
    projectId: 'thementr-f6c53',
    storageBucket: 'thementr-f6c53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYtC0fxwWerNDPRG-UG8rDAJbOczNmEFQ',
    appId: '1:873514032021:ios:2eeed4a69c75f1f541349c',
    messagingSenderId: '873514032021',
    projectId: 'thementr-f6c53',
    storageBucket: 'thementr-f6c53.appspot.com',
    iosClientId: '873514032021-i011bnup6mg7q7hmuuoo0i71lr31e711.apps.googleusercontent.com',
    iosBundleId: 'com.OptikkalTech.thementr',
  );
}
